<a href="https://colab.research.google.com/github/Leidyhdez/Mis_proyectos/blob/main/01_LeidyHernandez_PT_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **LEIDY HERNANDEZ VARGAS**
1 - Importar datos

Se usa la read_csv en la cual se le indica al programa la extension, ruta y codificación a usar.
La funcion enconding debido a la copatilidadad con el tipo de archivo recibido.
La funcion sep se encarga de hacer la cadena de comparacion de los argumantos, para este caso ";"

*1.1 Importa tabla PuntosInteres *

In [ ]:
from google.colab import files
from google.colab import drive
import pandas as pd
import numpy as np
from datetime import datetime

Ptos_int_V1 = "/content/drive/MyDrive/Colab Notebooks/Prueba_tecnica/PuntosInteres.csv"
Ptos_int = pd.read_csv(Ptos_int_V1, encoding='latin-1', sep=';')
output_file = "/content/PuntosInteres_output.csv"
Ptos_int.to_csv(output_file, index=False, encoding='latin-1', sep=';') # Use the DataFrame 'Ptos_int' to write to the CSV file

Ptos_int.shape
Ptos_int.head(5)

# Specify the output file path
##files.download(output_file) # Download the output file

   -73.9224858  4.5294102  pharmacy                    No hallado
0   -75.556054  10.396154  pharmacy                    No hallado
1   -75.561023  10.394204  pharmacy                    No hallado
2   -74.206402   4.715360  pharmacy  DroguerÐa Colsubsidio Funza
3   -75.578630   6.184220  pharmacy              Farmacia Pasteur
4   -74.056567   4.704550  pharmacy                    No hallado

In [ ]:
Ptos_int.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39899 entries, 0 to 39898
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   -73.9224858  39899 non-null  float64
 1   4.5294102    39899 non-null  float64
 2   pharmacy     39899 non-null  object
 3   No hallado   39898 non-null  object
dtypes: float64(2), object(2)
memory usage: 1.2+ MB

In [ ]:
encabezados = ['Longitud', 'Latitud', 'Lugar', 'Nombre_lugar']

Ptos_int.columns = encabezados

In [ ]:
PuntosInteres_V1 = "/content/sample_data/PuntosInteres_V1.csv"

output_csv_data = Ptos_int.to_csv(PuntosInteres_V1, index=False, encoding='latin-1', sep=';')
files.download(PuntosInteres_V1)

In [ ]:
Ptos_int.info()
Ptos_int.describe()
print(Ptos_int.isnull().sum())
Ptos_int.dropna(inplace=True)
Ptos_int.drop_duplicates(inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39899 entries, 0 to 39898
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Longitud      39899 non-null  float64
 1   Latitud       39899 non-null  float64
 2   Lugar         39899 non-null  object
 3   Nombre_lugar  39898 non-null  object
dtypes: float64(2), object(2)
memory usage: 1.2+ MB
Longitud        0
Latitud         0
Lugar           0
Nombre_lugar    1
dtype: int64

In [ ]:
resumen_columna_Ptosint = Ptos_int['Lugar'].describe()
print(resumen_columna_Ptosint)

count          39894
unique            84
top       restaurant
freq            7236
Name: Lugar, dtype: object

Identificacion de variable Lugar como valor agregado para analisis inicial,  la variable Nombre_lugar no represeta relevacia hasta el momento para el análisis

In [ ]:
##valores_distintos_col = Ptos_int['Lugar'].unique()
valores_distintos_col_1 = Ptos_int['Lugar'].value_counts().head(10)
print(valores_distintos_col_1)

Lugar
restaurant          7236
school              4584
supermarket         2394
pharmacy            2217
cafe                1980
fast_food           1909
bank                1837
fuel                1802
place_of_worship    1640
bar                 1271
Name: count, dtype: int64

*1.2 - Importa tabla test_precios_vivienda*

In [ ]:
from google.colab import files
from google.colab import drive
import pandas as pd
test_precios = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Prueba_tecnica/test_precios_vivienda.csv", encoding='latin-1', sep=';')
test_precios.shape
test_precios.head(5)

,id,fecha_aprobaciÃ³n,objeto,motivo,proposito,tipo_avaluo,tipo_credito,tipo_subsidio,departamento_inmueble,municipio_inmueble,...,area_terreno,valor_area_terreno,area_construccion,valor_area_construccion,area_otros,valor_area_otros,area_libre,valor_area_libre,Longitud,Latitud
0,2243,430.144.469.211.111,OriginaciÃ³n,CrÃ©dito hipotecario de vivienda,GarantÃ­a Hipotecaria,Hipotecario,Vivienda,NaN,MAGDALENA,SANTA MARTA,...,0,0,0,0,0,0,No,0,0.0,0.0
1,500,429.894.007.425.116,OriginaciÃ³n,CrÃ©dito hipotecario de vivienda,GarantÃ­a Hipotecaria,Hipotecario,Vivienda,NaN,MAGDALENA,CIENAGA,...,136,27200000,80,44800000,0,0,0,0,0.0,0.0
2,12884,NaN,OriginaciÃÂ³n,CrÃÂ©dito hipotecario de vivienda,GarantÃÂ­a Hipotecaria,Hipotecario,Vivienda,NaN,TOLIMA,MELGAR,...,0,0,0,0,348.23,90539800,No,0,-74.643.383,4.203.572
3,4019,430.486.908.754.861,OriginaciÃ³n,ActualizaciÃ³n de garantÃ­as,GarantÃ­a Hipotecaria,Hipotecario,Vivienda,NaN,CESAR,VALLEDUPAR,...,0,0,0,0,0,0,Si,0,0.0,0.0
4,11584,NaN,OriginaciÃÂ³n,CrÃÂ©dito hipotecario de vivienda,GarantÃÂ­a Hipotecaria,Hipotecario,Vivienda,NaN,HUILA,PITALITO,...,0,0,0,0,75.239.999.999.999.900,41382000,No,0,-760.631.391,18.413.391

In [ ]:
test_precios.info()
test_precios.describe()
print(test_precios.isnull().sum())
##Ptos_int.dropna(inplace=True)
##Ptos_int.drop_duplicates(inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 417 entries, 0 to 416
Columns: 218 entries, id to Latitud
dtypes: float64(3), int64(63), object(152)
memory usage: 710.3+ KB
id                     0
fecha_aprobaciÃ³n    234
objeto                 0
motivo                 0
proposito              0
                    ...
valor_area_otros       0
area_libre             0
valor_area_libre       0
Longitud               0
Latitud                0
Length: 218, dtype: int64

In [ ]:
test_precios.rename(columns={'fecha_aprobaciÃ³n': 'fecha_aprobado'}, inplace=True)
print(test_precios)
print(test_precios.fecha_aprobado)

        id       fecha_aprobado          objeto  \
0     2243  430.144.469.211.111    OriginaciÃ³n
1      500  429.894.007.425.116    OriginaciÃ³n
2    12884                  NaN  OriginaciÃÂ³n
3     4019  430.486.908.754.861    OriginaciÃ³n
4    11584                  NaN  OriginaciÃÂ³n
..     ...                  ...             ...
412  14877                  NaN  OriginaciÃÂ³n
413  11319                  NaN  OriginaciÃÂ³n
414   8095                  NaN  OriginaciÃÂ³n
415   7435              43158.0  OriginaciÃÂ³n
416  16318                  NaN  OriginaciÃÂ³n

                                 motivo                proposito  tipo_avaluo  \
0      CrÃ©dito hipotecario de vivienda    GarantÃ­a Hipotecaria  Hipotecario
1      CrÃ©dito hipotecario de vivienda    GarantÃ­a Hipotecaria  Hipotecario
2    CrÃÂ©dito hipotecario de vivienda  GarantÃÂ­a Hipotecaria  Hipotecario
3          ActualizaciÃ³n de garantÃ­as    GarantÃ­a Hipotecaria  Hipotecario
4    CrÃÂ©dito hipotecario de vivienda  GarantÃÂ­a Hipotecaria  Hipotecario
..                                  ...                      ...          ...
412  CrÃÂ©dito hipotecario de vivienda  GarantÃÂ­a Hipotecaria  Hipotecario
413                   Compra de cartera  GarantÃÂ­a Hipotecaria  Hipotecario
414  CrÃÂ©dito hipotecario de vivienda  GarantÃÂ­a Hipotecaria  Hipotecario
415  CrÃÂ©dito hipotecario de vivienda  GarantÃÂ­a Hipotecaria  Hipotecario
416                Colomext Hipotecario  GarantÃÂ­a Hipotecaria  Hipotecario

    tipo_credito tipo_subsidio departamento_inmueble municipio_inmueble  ...  \
0       Vivienda           NaN             MAGDALENA        SANTA MARTA  ...
1       Vivienda           NaN             MAGDALENA            CIENAGA  ...
2       Vivienda           NaN                TOLIMA             MELGAR  ...
3       Vivienda           NaN                 CESAR         VALLEDUPAR  ...
4       Vivienda           NaN                 HUILA           PITALITO  ...
..           ...           ...                   ...                ...  ...
412     Vivienda           NaN            BOLÃÂVAR          CARTAGENA  ...
413     Vivienda           NaN          CUNDINAMARCA             CAJICA  ...
414     Vivienda           VIS      BOGOTÃÂ, D. C.   BOGOTÃÂ, D. C.  ...
415     Vivienda      Gratuita             SANTANDER    BARRANCABERMEJA  ...
416     Vivienda           NaN             ANTIOQUIA              BELLO  ...

    area_terreno valor_area_terreno area_construccion valor_area_construccion  \
0              0                  0                 0                       0
1            136           27200000                80                44800000
2              0                  0                 0                       0
3              0                  0                 0                       0
4              0                  0                 0                       0
..           ...                ...               ...                     ...
412           84           33600000                44                39600000
413            0                  0                 0                       0
414           42           31500000             29.68                23447200
415           40           22000000                56                58240000
416            0                  0                 0                       0

                 area_otros valor_area_otros area_libre valor_area_libre  \
0                         0                0         No                0
1                         0                0          0                0
2                    348.23         90539800         No                0
3                         0                0         Si                0
4    75.239.999.999.999.900         41382000         No                0
..                      ...              ...        ...              ...
412                       0                0          0                0
413                       0                0         Si                0
414                       0                0          0                0
415                       0                0          0                0
416                       0                0         No                0

         Longitud      Latitud
0             0.0          0.0
1             0.0          0.0
2     -74.643.383    4.203.572
3             0.0          0.0
4    -760.631.391   18.413.391
..            ...          ...
412    -7.543.036    1.033.191
413  -740.423.059    4.920.316
414    -7.415.561    4.569.585
415  -746.104.578  104.637.422
416  -755.580.294   63.179.324

[417 rows x 218 columns]
0      430.144.469.211.111
1      429.894.007.425.116
2                      NaN
3      430.486.908.754.861
4                      NaN
              ...
412                    NaN
413                    NaN
414                    NaN
415                43158.0
416                    NaN
Name: fecha_aprobado, Length: 417, dtype: object

In [ ]:
test_precios['fecha_aprobado'] = test_precios['fecha_aprobado'].astype(float)

test_precios['fecha_aprobado'] = test_precios['fecha_aprobado'].apply(float)

print(test_precios.fecha_aprobado)

# Definir una función para convertir el formato
from datetime import datetime
def convertir_fecha(fecha_str):
    # Separar los componentes de la fecha
    partes = fecha_str.split('.')
    # Asumimos el formato es AÑO.MES.DÍA.HORA.MINUTO
    año = int(partes[0])
    mes = int(partes[1])
    dia = int(partes[2])
    hora = int(partes[3])
    minuto = int(partes[4])

    # Crear un objeto de fecha y hora
    fecha = datetime(año, mes, dia, hora, minuto)
    return fecha



# Aplicar la función al DataFrame
test_precios['fecha_aprobado'] = test_precios['fecha_aprobado'].apply(convertir_fecha)

# Verificar los cambios
print(test_precios.fecha_aprobado)



##test_precios['fecha_aprobado'] = pd.to_datetime(test_precios['fecha_aprobado'], format='%d/%m/%Y')  # Ajusta el formato según tus datos
##test_precios['fecha_aprobado'] = pd.to_datetime(test_precios['fecha_aprobado'], infer_datetime_format=True)

ValueError: could not convert string to float: '430.144.469.211.111'

In [ ]:
##print(test_precios.objeto).count
##Valida_col_test = test_precios['objeto'].unique()
Valida_col_test = test_precios['objeto'].value_counts().head(10)
print(Valida_col_test)

objeto
OriginaciÃÂ³n    285
OriginaciÃ³n      118
Remate             14
Name: count, dtype: int64

Con el fin de ajustar el modelo y las variables utiles se unifican datos relevantes en los nombres de columnas

a. **Objeto**:  Estandariza nombre comluma

In [ ]:
test_precios['objeto'].replace('OriginaciÃÂ³n', 'Originación', inplace=True)
test_precios['objeto'].replace('OriginaciÃ³n', 'Originación', inplace=True)
Valida_col_test = test_precios['objeto'].value_counts().head(10)
print(Valida_col_test)

objeto
Originación    403
Remate          14
Name: count, dtype: int64

b. **Motivo**: Estandariza

In [ ]:
Valida_col_test = test_precios['motivo'].value_counts().head(10)
print(Valida_col_test)
test_precios['motivo'].replace('CrÃÂ©dito hipotecario de vivienda', 'Credito Hipotec Vivienda', inplace=True)
test_precios['motivo'].replace('CrÃ©dito hipotecario de vivienda', 'Credito Hipotec Vivienda', inplace=True)
test_precios['motivo'].replace('ActualizaciÃ³n de garantÃ­as', 'Actualización Garantias', inplace=True)
test_precios['motivo'].replace('GarantÃ­a', 'Garantia', inplace=True)
Valida_col_test = test_precios['motivo'].value_counts().head(10)

motivo
Credito Hipotec Vivienda    295
Leasing Habitacional         39
Empleados                    34
Remates                      17
Colomext Hipotecario         11
Compra de cartera             8
Hipotecario Visto Bueno       6
Actualización Garantias       3
Leasing Visto Bueno           2
Garantia                      1
Name: count, dtype: int64

c. **Proposito**: Estandariza

In [ ]:
Valida_col_test = test_precios['proposito'].value_counts().head(10)
print(Valida_col_test)
test_precios['proposito'].replace('GarantÃÂ­a Hipotecaria', 'Garantía Hipotecaria', inplace=True)
test_precios['proposito'].replace('GarantÃ­a Hipotecaria', 'Garantía Hipotecaria', inplace=True)
test_precios['proposito'].replace('Garantia Hipotecaria', 'Garantía Hipotecaria', inplace=True)
test_precios['proposito'].replace('TransacciÃ³n Comercial de Venta', 'Transaccion Cial en Vta', inplace=True)

proposito
GarantÃÂ­a Hipotecaria            294
GarantÃ­a Hipotecaria              122
TransacciÃ³n Comercial de Venta      1
Name: count, dtype: int64

d. Recorre demas columnas para validar datos (consistencia vs necesidad)

In [ ]:
Valida_col_test = test_precios['tipo_avaluo'].value_counts().head(10)
print(Valida_col_test)

tipo_avaluo
Hipotecario    403
Remates         14
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['tipo_credito'].value_counts().head(10)
print(Valida_col_test)

tipo_credito
Vivienda                 412
Diferente de Vivienda      5
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['sector'].value_counts().head(10)
print(Valida_col_test)

sector
Urbano    402
Rural      15
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['alcantarillado_en_el_sector'].value_counts().head(10)
print(Valida_col_test)

alcantarillado_en_el_sector
Si    411
No      6
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['acueducto_en_el_sector'].value_counts().head(10)
print(Valida_col_test)

acueducto_en_el_sector
Si    415
No      2
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['gas_en_el_sector'].value_counts().head(10)
print(Valida_col_test)

gas_en_el_sector
Si    403
No     14
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['estrato'].value_counts().head(10)
print(Valida_col_test)

estrato
3            145
4            105
2             71
5             57
6             24
1             14
Comercial      1
Name: count, dtype: int64

Se intenta eliminar los caracteres especiales pero colab no reconoce unos de ellos por lo que se realiza con el reemplazar

In [ ]:
import re
Valida_col_test = test_precios['departamento_inmueble'].value_counts().head(10)

#función en python que hace uso de la libreria re, dicha función tiene como finalidad borrar los caracteres especiales
def eliminarCaracteres(texto):
  if isinstance(texto, str):
        return re.sub(r'[ ]', '', texto)
  return texto

for objeto in test_precios.select_dtypes(include=['object']).columns:
    test_precios['departamento_inmueble'] = test_precios['departamento_inmueble'].apply(eliminarCaracteres)

print(Valida_col_test)

departamento_inmueble
ANTIOQUIA           100
BOGOTÃÂ, D. C.     63
VALLE DEL CAUCA      35
BOGOTÃ, D. C.       26
CUNDINAMARCA         22
SANTANDER            18
MAGDALENA            17
ATLÃÂNTICO         16
META                 11
TOLIMA               10
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['departamento_inmueble'].value_counts().head(30)
print(Valida_col_test)
test_precios['departamento_inmueble'].replace('BOGOTÃÂ,D.C.', 'BOGOTA', inplace=True)
test_precios['departamento_inmueble'].replace('BOGOTÃ,D.C.', 'BOGOTA', inplace=True)
test_precios['departamento_inmueble'].replace('BOGOTÃ,D.C.', 'BOGOTA', inplace=True)
test_precios['departamento_inmueble'].replace('ATLÃÂNTICO', 'ATLANTICO', inplace=True)
test_precios['departamento_inmueble'].replace('NORTEDESANTANDER', 'NORTE DE SANTANDER', inplace=True)
test_precios['departamento_inmueble'].replace('BOLÃÂVAR', 'BOLIVAR', inplace=True)
test_precios['departamento_inmueble'].replace('BOYAC', 'BOYACA', inplace=True)
test_precios['departamento_inmueble'].replace('CRDOBA', 'CORDOBA', inplace=True)
test_precios['departamento_inmueble'].replace('CAQUET', 'CAQUETA', inplace=True)

departamento_inmueble
ANTIOQUIA             100
BOGOTA                 89
VALLEDELCAUCA          35
CUNDINAMARCA           22
SANTANDER              18
MAGDALENA              17
ATLANTICO              16
META                   11
TOLIMA                 10
NORTE DE SANTANDER      9
CESAR                   9
CALDAS                  9
RISARALDA               8
ATLÃNTICO              7
HUILA                   7
BOLIVAR                 7
CAUCA                   7
BOYACÃÂ               6
QUINDÃO                4
PUTUMAYO                4
NARIÃO                 3
NARIÃâO              3
QUINDÃÂO              3
ARAUCA                  2
CÃRDOBA                2
CAQUETÃÂ              2
CÃâRDOBA             2
BOYACÃ                 1
GUAVIARE                1
CAQUETÃ                1
Name: count, dtype: int64

demanda_interes:  variable  DÃÂ©bil se reemplzada por Nula (no hace sentido 9 datos)

In [ ]:
Valida_col_test = test_precios['demanda_interes'].value_counts().head(10)
print(Valida_col_test)

test_precios['demanda_interes'].replace('DÃÂ©bil', 'Nula', inplace=True)
test_precios['demanda_interes'].replace('DÃÂ©bil', 'Nula', inplace=True)
test_precios['demanda_interes'].replace('DÃ©bil', 'Nula', inplace=True)

demanda_interes
Media       335
Fuerte       60
Nula         13
DÃÂ©bil      5
DÃ©bil        4
Name: count, dtype: int64

Ajuste de datos para modelo

In [ ]:
Valida_col_test = test_precios['alcantarillado_en_el_predio'].value_counts().head(10)
print(Valida_col_test)
test_precios['alcantarillado_en_el_predio'].replace('0', 'No', inplace=True)

alcantarillado_en_el_predio
Si    399
No     18
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['acueducto_en_el_predio'].value_counts().head(10)
print(Valida_col_test)
test_precios['acueducto_en_el_predio'].replace('0', 'No', inplace=True)

acueducto_en_el_predio
Si    404
No     13
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['gas_en_el_predio'].value_counts().head(10)
print(Valida_col_test)
test_precios['gas_en_el_predio'].replace('0', 'No', inplace=True)

gas_en_el_predio
Si    365
No     43
0       9
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['energia_en_el_predio'].value_counts().head(10)
print(Valida_col_test)
test_precios['energia_en_el_predio'].replace('0', 'No', inplace=True)

energia_en_el_predio
Si    402
No     15
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['telefono_en_el_predio'].value_counts().head(10)
print(Valida_col_test)
test_precios['telefono_en_el_predio'].replace('0', 'No', inplace=True)

telefono_en_el_predio
Si    280
No    137
Name: count, dtype: int64

In [ ]:
Valida_col_test = test_precios['club_house'].value_counts().head(10)
print(Valida_col_test)
test_precios['club_house'].replace('0', 'No', inplace=True)

club_house
No    281
0     106
Si     30
Name: count, dtype: int64

Datos menos relevantes para el modelo que se ajustan a necesidad

In [ ]:
test_precios['rph'].replace('0', 'No', inplace=True)
test_precios['porteria'].replace('0', 'No', inplace=True)
test_precios['citofono'].replace('0', 'No', inplace=True)
test_precios['bicicletero'].replace('0', 'No', inplace=True)
test_precios['tanque_de_agua'].replace('0', 'No', inplace=True)
test_precios['club_house'].replace('0', 'No', inplace=True)
test_precios['garaje_visitantes'].replace('0', 'No', inplace=True)
test_precios['vigilancia_privada'].replace('0', 'No', inplace=True)
test_precios['tipo_vigilancia'].replace('0', 'Sin informacion', inplace=True)
test_precios['administracion'].replace('0', 'No', inplace=True)
test_precios['garaje_cubierto_1'].replace('0', 'No', inplace=True)
test_precios['garaje_doble_1'].replace('0', 'No', inplace=True)
test_precios['garaje_paralelo_1'].replace('0', 'No', inplace=True)
test_precios['garaje_servidumbre_1'].replace('0', 'No', inplace=True)
test_precios['garaje_cubierto_2'].replace('0', 'No', inplace=True)
test_precios['garaje_doble_2'].replace('0', 'No', inplace=True)
test_precios['garaje_paralelo_2'].replace('0', 'No', inplace=True)
test_precios['garaje_cubierto_3'].replace('0', 'No', inplace=True)
test_precios['garaje_doble_3'].replace('0', 'No', inplace=True)
test_precios['tipo_deposito'].replace('0', 'Sin informacion', inplace=True)
test_precios['estar_habitacion'].replace('2', '0', inplace=True)
test_precios['teatrino'].replace('0', 'No', inplace=True)

In [ ]:
test_precios.info()
test_precios_respaldo = test_precios

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 417 entries, 0 to 416
Columns: 218 entries, id to Latitud
dtypes: float64(3), int64(63), object(152)
memory usage: 710.3+ KB

In [ ]:
test_precios['area_privada'] = pd.to_numeric(test_precios['area_privada'], errors='coerce')
test_precios.area_privada = test_precios.area_privada.astype(float)

test_precios.area_privada.describe()

count     290.000000
mean       60.945310
std       121.135175
min         0.000000
25%         0.000000
50%        52.930000
75%        82.625000
max      1869.000000
Name: area_privada, dtype: float64

In [ ]:
test_precios['area_valorada'] = pd.to_numeric(test_precios['area_valorada'], errors='coerce')
test_precios.area_valorada = test_precios.area_valorada.astype(float)

test_precios.area_valorada.describe()

count      264.000000
mean       578.396883
std       5544.983474
min          0.000000
25%         55.917500
50%         78.750000
75%        111.000000
max      64146.000000
Name: area_valorada, dtype: float64

e. Tratamiento de datos para cambio a variables categoricas

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Identifica las columnas categóricas
columnas_categoricas = ["barrio_legal", "paradero", "alumbrado", "arborizacion", "alamedas", "ciclo_rutas", "alcantarillado_en_el_predio",
                        "acueducto_en_el_predio", "gas_en_el_predio", "energia_en_el_predio", "telefono_en_el_predio", "rph", "porteria",
                        "citofono", "piscina", "tanque_de_agua", "club_house", "sauna", "vigilancia_privada", "administracion", "club_house"]

# Crea instancias de `LabelEncoder`
encoder = LabelEncoder()

# Aplica la codificación binaria
for columna in columnas_categoricas:
    test_precios['barrio_legal'] = encoder.fit_transform(test_precios['barrio_legal'])
    test_precios['paradero'] = encoder.fit_transform(test_precios['paradero'])
    test_precios['alumbrado'] = encoder.fit_transform(test_precios['paradero'])
    test_precios['arborizacion'] = encoder.fit_transform(test_precios['arborizacion'])
    test_precios['ciclo_rutas'] = encoder.fit_transform(test_precios['ciclo_rutas'])
    test_precios['alcantarillado_en_el_predio'] = encoder.fit_transform(test_precios['alcantarillado_en_el_predio'])
    test_precios['acueducto_en_el_predio'] = encoder.fit_transform(test_precios['acueducto_en_el_predio'])
    test_precios['gas_en_el_predio'] = encoder.fit_transform(test_precios['gas_en_el_predio'])
    test_precios['energia_en_el_predio'] = encoder.fit_transform(test_precios['energia_en_el_predio'])
    test_precios['telefono_en_el_predio'] = encoder.fit_transform(test_precios['telefono_en_el_predio'])
    test_precios['rph'] = encoder.fit_transform(test_precios['rph'])
    test_precios['piscina'] = encoder.fit_transform(test_precios['piscina'])
    test_precios['tanque_de_agua'] = encoder.fit_transform(test_precios['tanque_de_agua'])
    test_precios['club_house'] = encoder.fit_transform(test_precios['club_house'])
    test_precios['sauna'] = encoder.fit_transform(test_precios['sauna'])
    test_precios['vigilancia_privada'] = encoder.fit_transform(test_precios['vigilancia_privada'])
    test_precios['administracion'] = encoder.fit_transform(test_precios['administracion'])
    test_precios['club_house'] = encoder.fit_transform(test_precios['club_house'])
    test_precios['porteria'] = encoder.fit_transform(test_precios['porteria'])
    test_precios['sometido_a_propiedad_horizontal'] = encoder.fit_transform(test_precios['sometido_a_propiedad_horizontal'])
    test_precios['citofono'] = encoder.fit_transform(test_precios['citofono'])
    test_precios['bicicletero'] = encoder.fit_transform(test_precios['bicicletero'])
    test_precios['garaje_visitantes'] = encoder.fit_transform(test_precios['garaje_visitantes'])
    test_precios['teatrino'] = encoder.fit_transform(test_precios['teatrino'])

# Verifica la codificación
print(test_precios.barrio_legal)
print(test_precios.alumbrado)
print(test_precios.arborizacion)
print(test_precios.ciclo_rutas)
print(test_precios.alcantarillado_en_el_predio)
print(test_precios.gas_en_el_predio)
print(test_precios.energia_en_el_predio)
print(test_precios.telefono_en_el_predio)
print(test_precios.rph)
print(test_precios.piscina)
print(test_precios.tanque_de_agua)
print(test_precios.club_house)
print(test_precios.sauna)
print(test_precios.vigilancia_privada)
print(test_precios.administracion)
print(test_precios.club_house)

0      1
1      0
2      1
3      1
4      1
      ..
412    1
413    1
414    1
415    1
416    1
Name: barrio_legal, Length: 417, dtype: int64
0      1
1      1
2      1
3      0
4      0
      ..
412    0
413    1
414    1
415    0
416    1
Name: alumbrado, Length: 417, dtype: int64
0      1
1      1
2      1
3      1
4      0
      ..
412    1
413    1
414    1
415    1
416    1
Name: arborizacion, Length: 417, dtype: int64
0      0
1      0
2      0
3      0
4      0
      ..
412    0
413    1
414    1
415    0
416    0
Name: ciclo_rutas, Length: 417, dtype: int64
0      1
1      1
2      1
3      1
4      1
      ..
412    1
413    1
414    1
415    1
416    1
Name: alcantarillado_en_el_predio, Length: 417, dtype: int64
0      1
1      1
2      0
3      1
4      0
      ..
412    1
413    1
414    1
415    1
416    1
Name: gas_en_el_predio, Length: 417, dtype: int64
0      1
1      1
2      1
3      1
4      1
      ..
412    1
413    1
414    1
415    1
416    1
Name: energia_en_el_predio, Length: 417, dtype: int64
0      0
1      0
2      0
3      0
4      0
      ..
412    1
413    1
414    1
415    1
416    0
Name: telefono_en_el_predio, Length: 417, dtype: int64
0      0
1      0
2      1
3      1
4      1
      ..
412    0
413    1
414    0
415    0
416    1
Name: rph, Length: 417, dtype: int64
0      2
1      0
2      2
3      1
4      2
      ..
412    0
413    2
414    0
415    0
416    2
Name: piscina, Length: 417, dtype: int64
0      1
1      0
2      0
3      0
4      1
      ..
412    0
413    0
414    0
415    0
416    0
Name: tanque_de_agua, Length: 417, dtype: int64
0      1
1      0
2      0
3      0
4      0
      ..
412    0
413    1
414    0
415    0
416    0
Name: club_house, Length: 417, dtype: int64
0      2
1      0
2      1
3      1
4      1
      ..
412    0
413    2
414    0
415    0
416    2
Name: sauna, Length: 417, dtype: int64
0      1
1      0
2      1
3      0
4      0
      ..
412    0
413    1
414    0
415    0
416    1
Name: vigilancia_privada, Length: 417, dtype: int64
0      1
1      0
2      1
3      0
4      1
      ..
412    0
413    1
414    0
415    0
416    1
Name: administracion, Length: 417, dtype: int64
0      1
1      0
2      0
3      0
4      0
      ..
412    0
413    1
414    0
415    0
416    0
Name: club_house, Length: 417, dtype: int64

Creacion nuevas variables

In [ ]:
Valor_metro_cuadrado = 'Metro_cuadrado'

test_precios[Valor_metro_cuadrado] = test_precios['valor_area_privada'] / test_precios['area_privada'].astype(float)

In [ ]:
test_precios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 417 entries, 0 to 416
Columns: 219 entries, id to Metro_cuadrado
dtypes: float64(6), int64(86), object(127)
memory usage: 713.6+ KB

In [ ]:
print(test_precios.describe())
# Guardar las predicciones en un nuevo archivo
test_precios.to_csv('test_precios.csv', index=False)

# Descargar el archivo
files.download('test_precios.csv')

                 id  barrio_legal    paradero   alumbrado  arborizacion  \
count    417.000000    417.000000  417.000000  417.000000    417.000000
mean    8787.635492      0.947242    0.784173    0.784173      0.832134
std     5136.304089      0.223818    0.411889    0.411889      0.374196
min       11.000000      0.000000    0.000000    0.000000      0.000000
25%     4338.000000      1.000000    1.000000    1.000000      1.000000
50%     8799.000000      1.000000    1.000000    1.000000      1.000000
75%    13057.000000      1.000000    1.000000    1.000000      1.000000
max    18270.000000      1.000000    1.000000    1.000000      1.000000

       ciclo_rutas  alcantarillado_en_el_predio  acueducto_en_el_predio  \
count   417.000000                   417.000000              417.000000
mean      0.247002                     0.956835                0.968825
std       0.431786                     0.203474                0.173999
min       0.000000                     0.000000                0.000000
25%       0.000000                     1.000000                1.000000
50%       0.000000                     1.000000                1.000000
75%       0.000000                     1.000000                1.000000
max       1.000000                     1.000000                1.000000

       gas_en_el_predio  energia_en_el_predio  ...  metodo_valuacion_4  \
count        417.000000            417.000000  ...               417.0
mean           0.875300              0.964029  ...                 0.0
std            0.330776              0.186442  ...                 0.0
min            0.000000              0.000000  ...                 0.0
25%            1.000000              1.000000  ...                 0.0
50%            1.000000              1.000000  ...                 0.0
75%            1.000000              1.000000  ...                 0.0
max            1.000000              1.000000  ...                 0.0

       concepto_del_metodo_4  area_privada  valor_area_privada  \
count                  417.0    290.000000        4.170000e+02
mean                     0.0     60.945310        1.967126e+08
std                      0.0    121.135175        2.299914e+08
min                      0.0      0.000000        0.000000e+00
25%                      0.0      0.000000        0.000000e+00
50%                      0.0     52.930000        1.485000e+08
75%                      0.0     82.625000        2.661440e+08
max                      0.0   1869.000000        2.264800e+09

       valor_area_garaje  valor_area_deposito  valor_area_construccion  \
count       4.170000e+02         4.170000e+02             4.170000e+02
mean        8.380827e+07         4.037774e+05             2.692603e+07
std         1.566751e+09         1.354450e+06             6.572839e+07
min         0.000000e+00         0.000000e+00             0.000000e+00
25%         0.000000e+00         0.000000e+00             0.000000e+00
50%         0.000000e+00         0.000000e+00             0.000000e+00
75%         1.500000e+07         0.000000e+00             1.890000e+07
max         3.200000e+10         1.140000e+07             7.950000e+08

       valor_area_otros  valor_area_libre  Metro_cuadrado
count      4.170000e+02      4.170000e+02    1.850000e+02
mean       5.897384e+06      2.924783e+06    3.016216e+06
std        4.439847e+07      2.339788e+07    1.345767e+06
min        0.000000e+00      0.000000e+00    3.150000e+05
25%        0.000000e+00      0.000000e+00    2.120000e+06
50%        0.000000e+00      0.000000e+00    2.700000e+06
75%        0.000000e+00      0.000000e+00    3.750000e+06
max        5.901220e+08      3.166856e+08    8.730000e+06

[8 rows x 92 columns]

In [ ]:
# Crea un  archivo que contenga datos relevante para el mmodelo

test_final_columnas = ['estrato', 'barrio_legal', 'paradero', 'alumbrado', 'arborizacion', 'ciclo_rutas', 'sometido_a_propiedad_horizontal',
                       'porteria', 'citofono', 'bicicletero', 'piscina', 'tanque_de_agua', 'club_house', 'garaje_visitantes',
                       'teatrino', 'sauna', 'vigilancia_privada', 'tipo_vigilancia', 'administracion', 'vetustez', 'habitaciones',
                       'estar_habitacion', 'cuarto_servicio', 'closet', 'sala', 'comedor', 'bano_privado', 'bano_social',
                       'bano_servicio', 'cocina', 'estudio', 'balcon', 'terraza', 'patio_interior', 'jardin', 'zona_de_ropas',
                       'zona_verde_privada', 'local', 'oficina', 'bodega', 'tipo_garaje', 'numero_total_de_garajes', 'area_privada',
                       'valor_area_privada', 'area_garaje', 'valor_area_garaje', 'area_deposito', 'valor_area_deposito', 'area_terreno',
                       'valor_area_terreno', 'area_construccion', 'valor_area_construccion', 'area_otros', 'valor_area_otros',
                       'area_libre', 'valor_area_libre', 'Longitud', 'Latitud']

test_info_modelo = test_precios[test_final_columnas]

test_info_modelo.describe()

,barrio_legal,paradero,alumbrado,arborizacion,ciclo_rutas,sometido_a_propiedad_horizontal,porteria,citofono,bicicletero,piscina,...,oficina,bodega,numero_total_de_garajes,area_privada,valor_area_privada,valor_area_garaje,valor_area_deposito,valor_area_construccion,valor_area_otros,valor_area_libre
count,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,...,417.000000,417.000000,417.000000,290.000000,4.170000e+02,4.170000e+02,4.170000e+02,4.170000e+02,4.170000e+02,4.170000e+02
mean,0.947242,0.784173,0.784173,0.832134,0.247002,0.071942,0.071942,0.071942,0.071942,1.031175,...,0.002398,0.016787,0.563549,60.945310,1.967126e+08,8.380827e+07,4.037774e+05,2.692603e+07,5.897384e+06,2.924783e+06
std,0.223818,0.411889,0.411889,0.374196,0.431786,0.258703,0.258703,0.258703,0.258703,0.734773,...,0.048970,0.175976,0.617388,121.135175,2.299914e+08,1.566751e+09,1.354450e+06,6.572839e+07,4.439847e+07,2.339788e+07
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,1.000000,52.930000,1.485000e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,...,0.000000,0.000000,1.000000,82.625000,2.661440e+08,1.500000e+07,0.000000e+00,1.890000e+07,0.000000e+00,0.000000e+00
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,...,1.000000,3.000000,3.000000,1869.000000,2.264800e+09,3.200000e+10,1.140000e+07,7.950000e+08,5.901220e+08,3.166856e+08

In [ ]:
Valida_col_test = test_precios['valor_area_privada'].value_counts().head(100)
print(Valida_col_test)

valor_area_privada
0            106
196840000      2
239916600      1
194724000      1
155568000      1
            ...
296582615      1
139583640      1
179596500      1
219960000      1
396540000      1
Name: count, Length: 100, dtype: int64

*1.3 - Importa train_precios_vivienda*

In [ ]:
from google.colab import files
from google.colab import drive
import pandas as pd
train_precios = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Prueba_tecnica/train_precios_vivienda_trabajo1.csv", encoding='latin-1', sep=';')
train_precios.shape
train_precios.head(5)

<ipython-input-329-be90bf407c06>:4: DtypeWarning: Columns (22,154,160,161,162,163,164,165,168,169,170,171,176,177,186,188,192,206,208,210,222) have mixed types. Specify dtype option on import or set low_memory=False.
  train_precios = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Prueba_tecnica/train_precios_vivienda_trabajo1.csv", encoding='latin-1', sep=';')

,llave_prim,id,fecha_aprobaciÃ³n,objeto,motivo,proposito,tipo_avaluo,tipo_credito,tipo_subsidio,departamento_inmueble,...,area_otros,valor_area_otros,area_libre,valor_area_libre,valor_total_avaluo,valor_uvr,valor_avaluo_en_uvr,Longitud,Latitud,Unnamed: 222
0,2798,4031,430.487.879.571.875,Remate,Remates,GarantÃ­a Hipotecaria,Remates,Diferente de Vivienda,NaN,TOLIMA,...,0,0.0,0,0,12,2520727,"47605,31",0.0,0.0,NaN
1,10821,15462,NaN,OriginaciÃÂ³n,Colomext Hipotecario,GarantÃÂ­a Hipotecaria,Hipotecario,Vivienda,NaN,ANTIOQUIA,...,0,0.0,No,0,"13,415745",25.963.979.999.999.900,51670.6,-755.982.993,62.251.357,NaN
2,882,1275,429.995.422.018.403,OriginaciÃ³n,CrÃ©dito hipotecario de vivienda,GarantÃ­a Hipotecaria,Hipotecario,Vivienda,Gratuita,CAUCA,...,0,0.0,0,0,"15,75",2517095,"62572,13",0.0,0.0,NaN
3,8465,12105,NaN,OriginaciÃÂ³n,CrÃÂ©dito hipotecario de vivienda,GarantÃÂ­a Hipotecaria,Hipotecario,Vivienda,NaN,NARIÃâO,...,0,0.0,0,0,"16,500127",25.796.370.000.000.000,63962.98,-77.280.189,1.194.269,NaN
4,1815,2584,430.204.924.126.968,OriginaciÃ³n,CrÃ©dito hipotecario de vivienda,GarantÃ­a Hipotecaria,Hipotecario,Vivienda,NaN,BOLÃVAR,...,0,0.0,0,0,"19,9117",2519561,"79028,45",0.0,0.0,NaN

In [ ]:
print(train_precios.isnull().sum())

llave_prim                 0
id                         0
fecha_aprobaciÃ³n       6760
objeto                     0
motivo                     0
                       ...
valor_uvr               1141
valor_avaluo_en_uvr     1141
Longitud                1141
Latitud                 1142
Unnamed: 222           11420
Length: 223, dtype: int64

In [ ]:
import numpy as np

train_precios['valor_total_avaluo'] = pd.to_numeric(train_precios['valor_total_avaluo'], errors='coerce')
train_precios.valor_total_avaluo = train_precios.valor_total_avaluo.astype(float)

train_precios.valor_total_avaluo.count()

186

In [ ]:
train_precios.valor_total_avaluo.count()
train_precios.valor_total_avaluo.describe()

## se cambio valor desde la fuente a millones para trabajo en colab ejmplo 12.000.000 cargado a 12 MM cifras sera dadas en millones

count     186.000000
mean      256.043011
std       243.987213
min        12.000000
25%       114.750000
50%       175.000000
75%       295.750000
max      1764.000000
Name: valor_total_avaluo, dtype: float64

In [ ]:
##print(test_precios.objeto).count
##Valida_col_test = test_precios['objeto'].unique()
Valida_col_train = train_precios['objeto'].value_counts().head(10)
print(Valida_col_train)

objeto
OriginaciÃÂ³n    8230
OriginaciÃ³n      2854
Remate             337
Name: count, dtype: int64

In [ ]:
train_precios['objeto'].replace('OriginaciÃÂ³n', 'Originación', inplace=True)
train_precios['objeto'].replace('OriginaciÃ³n', 'Originación', inplace=True)
Valida_col_train = train_precios['objeto'].value_counts().head(10)
print(Valida_col_train)

objeto
Originación    11084
Remate           337
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['motivo'].value_counts().head(10)
print(Valida_col_train)

motivo
CrÃÂ©dito hipotecario de vivienda    6194
CrÃ©dito hipotecario de vivienda      2247
Leasing Habitacional                   970
Empleados                              707
Remates                                376
Colomext Hipotecario                   311
Compra de cartera                      237
Hipotecario Visto Bueno                116
DaciÃÂ³n en Pago                       77
GarantÃ­a                               54
Name: count, dtype: int64

In [ ]:
train_precios['motivo'].replace('CrÃÂ©dito hipotecario de vivienda', 'Credito Hipotec Vivienda', inplace=True)
train_precios['motivo'].replace('CrÃ©dito hipotecario de vivienda', 'Credito Hipotec Vivienda', inplace=True)
train_precios['motivo'].replace('ActualizaciÃ³n de garantÃ­as', 'Actualización Garantias', inplace=True)
train_precios['motivo'].replace('GarantÃ­a', 'Garantia', inplace=True)
train_precios['motivo'].replace('DaciÃÂ³n en Pago', 'Dacion en pago', inplace=True)
train_precios['motivo'].replace('DaciÃ³n en Pago', 'Dacion en pago', inplace=True)
train_precios['motivo'].replace('ActualizaciÃÂ³n de garantÃÂ­as', 'Actualización Garantias', inplace=True)
train_precios['motivo'].replace('CrÃÂ©dito Comercial', 'Credito comercial', inplace=True)
train_precios['motivo'].replace('CrÃ©dito Comercial', 'Credito comercial', inplace=True)
Valida_col_train = train_precios['motivo'].value_counts().head(30)
print(Valida_col_train)

motivo
Credito Hipotec Vivienda                  8441
Leasing Habitacional                       970
Empleados                                  707
Remates                                    376
Colomext Hipotecario                       311
Compra de cartera                          237
Dacion en pago                             121
Hipotecario Visto Bueno                    116
Actualización Garantias                     62
Garantia                                    54
Leasing Visto Bueno                         13
Credito comercial                            7
Leasing Comercial                            3
Reformas                                     1
0                                            1
Leasing Inmobiliario - Persona Natural       1
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['proposito'].value_counts().head(10)
print(Valida_col_train)

proposito
Garantía Hipotecaria       11227
Transaccion Cial de Vta      149
Valor Asegurable              41
Sin informacion                4
Name: count, dtype: int64

In [ ]:
train_precios['proposito'].replace('GarantÃÂ­a Hipotecaria', 'Garantía Hipotecaria', inplace=True)
train_precios['proposito'].replace('GarantÃ­a Hipotecaria', 'Garantía Hipotecaria', inplace=True)
train_precios['proposito'].replace('TransacciÃÂ³n Comercial de Venta', 'Transaccion Cial de Vta', inplace=True)
train_precios['proposito'].replace('TransacciÃ³n Comercial de Venta', 'Transaccion Cial de Vta', inplace=True)
train_precios['proposito'].replace('0', 'Sin informacion', inplace=True)

print(Valida_col_train)

proposito
GarantÃÂ­a Hipotecaria              8347
GarantÃ­a Hipotecaria                2880
TransacciÃÂ³n Comercial de Venta     115
Valor Asegurable                       41
TransacciÃ³n Comercial de Venta        34
0                                       4
Name: count, dtype: int64

In [ ]:
print(Valida_col_train)

tipo_avaluo
Hipotecario    11082
Remates          339
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['tipo_avaluo'].value_counts().head(10)
print(Valida_col_train)

tipo_avaluo
Hipotecario    11082
Remates          339
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['tipo_credito'].value_counts().head(10)
print(Valida_col_train)

tipo_credito
Vivienda                 11126
Diferente de Vivienda      295
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['departamento_inmueble'].value_counts().head(30)
print(Valida_col_train)

departamento_inmueble
ANTIOQUIA             2989
BOGOTA                2379
VALLE DEL CAUCA       1085
CUNDINAMARCA           604
SANTANDER              532
ATLANTICO              485
TOLIMA                 350
RISARALDA              299
BOLIVAR                289
NORTE DE SANTANDER     246
CALDAS                 240
HUILA                  230
META                   222
BOYACA                 194
CORDOBA                186
CESAR                  170
MAGDALENA              168
QUINDIO                110
NARIÃâO             106
SUCRE                  106
CAUCA                   97
CASANARE                64
QUINDÃO                59
NARIÑO                  43
CAQUETA                 36
PUTUMAYO                36
LA GUAJIRA              33
CAQUETÃ                25
GUAVIARE                12
AMAZONAS                 8
Name: count, dtype: int64

In [ ]:
train_precios['departamento_inmueble'].replace('BOGOTÃÂ, D. C.', 'BOGOTA', inplace=True)
train_precios['departamento_inmueble'].replace('BOGOTÃ,D.C.', 'BOGOTA', inplace=True)
train_precios['departamento_inmueble'].replace('BOGOTÃ, D. C.', 'BOGOTA', inplace=True)
train_precios['departamento_inmueble'].replace('ATLÃÂNTICO', 'ATLANTICO', inplace=True)
train_precios['departamento_inmueble'].replace('NORTEDESANTANDER', 'NORTE DE SANTANDER', inplace=True)
train_precios['departamento_inmueble'].replace('BOLÃÂVAR', 'BOLIVAR', inplace=True)
train_precios['departamento_inmueble'].replace('BOYAC', 'BOYACA', inplace=True)
train_precios['departamento_inmueble'].replace('CRDOBA', 'CORDOBA', inplace=True)
train_precios['departamento_inmueble'].replace('CÃâRDOBA', 'CORDOBA', inplace=True)
train_precios['departamento_inmueble'].replace('BOYACÃÂ', 'BOYACA', inplace=True)
train_precios['departamento_inmueble'].replace('ATLÃNTICO', 'ATLANTICO', inplace=True)
train_precios['departamento_inmueble'].replace('QUINDÃÂO', 'QUINDIO', inplace=True)
train_precios['departamento_inmueble'].replace('NARIÃO', 'NARIÑO', inplace=True)
train_precios['departamento_inmueble'].replace('CÃRDOBA', 'CORDOBA', inplace=True)
train_precios['departamento_inmueble'].replace('CAQUETÃÂ', 'CAQUETA', inplace=True)
train_precios['departamento_inmueble'].replace('BOYACÃ', 'BOYACA', inplace=True)
train_precios['departamento_inmueble'].replace('BOLÃVAR', 'BOLIVAR', inplace=True)
train_precios['departamento_inmueble'].replace('GUAINÃÂA', 'GUAINIA', inplace=True)

In [ ]:
Valida_col_train = train_precios['demanda_interes'].value_counts().head(10)
print(Valida_col_train)

demanda_interes
Media       9269
Fuerte      1430
Nula         716
Vivienda       1
Name: count, dtype: int64

In [ ]:
train_precios['demanda_interes'].replace('DÃÂ©bil', 'Nula', inplace=True)
train_precios['demanda_interes'].replace('DÃÂ©bil', 'Nula', inplace=True)
train_precios['demanda_interes'].replace('DÃ©bil', 'Nula', inplace=True)

In [ ]:
Valida_col_train = train_precios['alcantarillado_en_el_predio'].value_counts().head(10)
print(Valida_col_train)
train_precios['alcantarillado_en_el_predio'].replace('0', 'No', inplace=True)

alcantarillado_en_el_predio
Si    10394
No      409
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['acueducto_en_el_predio'].value_counts().head(10)
print(Valida_col_train)
train_precios['acueducto_en_el_predio'].replace('0', 'No', inplace=True)

acueducto_en_el_predio
Si    10448
No      355
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['gas_en_el_predio'].value_counts().head(10)
print(Valida_col_train)
train_precios['gas_en_el_predio'].replace('0', 'No', inplace=True)

gas_en_el_predio
Si    9711
No    1092
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['energia_en_el_predio'].value_counts().head(10)
print(Valida_col_train)
train_precios['energia_en_el_predio'].replace('0', 'No', inplace=True)

energia_en_el_predio
Si    10404
No      399
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['telefono_en_el_predio'].value_counts().head(10)
print(Valida_col_train)
train_precios['telefono_en_el_predio'].replace('0', 'No', inplace=True)

telefono_en_el_predio
Si    6920
No    3883
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['club_house'].value_counts().head(10)
print(Valida_col_train)
train_precios['club_house'].replace('0', 'No', inplace=True)

club_house
No    9988
Si     528
Name: count, dtype: int64

In [ ]:
Valida_col_train = train_precios['barrio_legal'].value_counts().head(10)
print(Valida_col_train)
train_precios['barrio_legal'].replace('3', 'Si', inplace=True)

barrio_legal
Si    10944
No      472
Name: count, dtype: int64

In [ ]:
train_precios['rph'].replace('0', 'No', inplace=True)
train_precios['porteria'].replace('0', 'No', inplace=True)
train_precios['citofono'].replace('0', 'No', inplace=True)
train_precios['bicicletero'].replace('0', 'No', inplace=True)
train_precios['tanque_de_agua'].replace('0', 'No', inplace=True)
train_precios['club_house'].replace('0', 'No', inplace=True)
train_precios['garaje_visitantes'].replace('0', 'No', inplace=True)
train_precios['vigilancia_privada'].replace('0', 'No', inplace=True)
train_precios['tipo_vigilancia'].replace('0', 'Sin informacion', inplace=True)
train_precios['administracion'].replace('0', 'No', inplace=True)
train_precios['garaje_cubierto_1'].replace('0', 'No', inplace=True)
train_precios['garaje_doble_1'].replace('0', 'No', inplace=True)
train_precios['garaje_paralelo_1'].replace('0', 'No', inplace=True)
train_precios['garaje_servidumbre_1'].replace('0', 'No', inplace=True)
train_precios['garaje_cubierto_2'].replace('0', 'No', inplace=True)
train_precios['garaje_doble_2'].replace('0', 'No', inplace=True)
train_precios['garaje_paralelo_2'].replace('0', 'No', inplace=True)
train_precios['garaje_cubierto_3'].replace('0', 'No', inplace=True)
train_precios['garaje_doble_3'].replace('0', 'No', inplace=True)
train_precios['tipo_deposito'].replace('0', 'Sin informacion', inplace=True)
train_precios['estar_habitacion'].replace('2', '0', inplace=True)
train_precios['teatrino'].replace('0', 'No', inplace=True)

In [ ]:
train_precios.info()
train_precios_respaldo = train_precios

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11421 entries, 0 to 11420
Columns: 223 entries, llave_prim to Unnamed: 222
dtypes: float64(41), int64(3), object(179)
memory usage: 19.4+ MB

In [ ]:
train_precios['area_privada'] = pd.to_numeric(train_precios['area_privada'], errors='coerce')
train_precios.area_privada = train_precios.area_privada.astype(float)

train_precios.area_privada.describe()

count      7644.000000
mean         89.457241
std        1967.708728
min           0.000000
25%           0.000000
50%          51.985000
75%          76.842500
max      160998.340000
Name: area_privada, dtype: float64

In [ ]:
train_precios.vetustez.describe()

train_precios.vetustez = train_precios.vetustez.astype(int)
print(train_precios.vetustez)  # Esto mostrará 3 (sin decimales)

0        52
1         0
2         3
3        34
4        10
         ..
11416     0
11417     0
11418     0
11419     0
11420     9
Name: vetustez, Length: 11421, dtype: int64

In [ ]:
train_precios['area_valorada'] = pd.to_numeric(train_precios['area_valorada'], errors='coerce')
train_precios.area_valorada = train_precios.area_valorada.astype(float)

print(train_precios.area_valorada)

0          0.00
1         57.21
2          0.00
3        127.20
4           NaN
          ...
11416       NaN
11417       NaN
11418     28.30
11419       NaN
11420     57.40
Name: area_valorada, Length: 11421, dtype: float64

In [ ]:
train_precios.describe()

,llave_prim,id,observaciones_altura_permitida,unidades,contadores_agua,contadores_luz,accesorios,area_valorada,numero_piso,numero_de_edificios,...,numero_total_depositos,numero_deposito_3,matricula_inmobiliaria_deposito_3,numero_deposito_4,matricula_inmobiliaria_deposito_4,numero_deposito_5,matricula_inmobiliaria_deposito_5,area_privada,valor_area_otros,valor_total_avaluo
count,11421.000000,11421.000000,10803.000000,10803.000000,10803.000000,10803.000000,10803.000000,7419.000000,10516.000000,10516.000000,...,10380.000000,10380.000000,10378.0,10380.000000,10379.0,10380.0,10380.0,7644.000000,1.028000e+04,186.000000
mean,6507.941511,9296.717625,0.693048,0.102472,0.056003,0.060724,0.069518,902.451244,3.658235,4.969665,...,0.148362,0.010405,0.0,0.007322,0.0,0.0,0.0,89.457241,4.533289e+06,256.043011
std,3683.836440,5250.836536,1.444465,1.021504,0.937854,0.943711,0.591302,11120.495059,5.043639,12.082248,...,0.369562,0.804223,0.0,0.745959,0.0,0.0,0.0,1967.708728,4.335262e+07,243.987213
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,12.000000
25%,3340.000000,4800.000000,0.000000,0.000000,0.000000,0.000000,0.000000,56.020000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,114.750000
50%,6524.000000,9317.000000,0.000000,0.000000,0.000000,0.000000,0.000000,76.500000,2.000000,1.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,51.985000,0.000000e+00,175.000000
75%,9696.000000,13843.000000,0.000000,0.000000,0.000000,0.000000,0.000000,112.165000,5.000000,4.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,76.842500,0.000000e+00,295.750000
max,12856.000000,18331.000000,25.000000,92.000000,92.000000,92.000000,46.000000,376582.000000,99.000000,99.000000,...,4.000000,75.000000,0.0,76.000000,0.0,0.0,0.0,160998.340000,1.192110e+09,1764.000000

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Identifica las columnas categóricas
columnas_categoricas = ["barrio_legal", "paradero", "alumbrado", "arborizacion", "alamedas", "ciclo_rutas", "alcantarillado_en_el_predio",
                        "acueducto_en_el_predio", "gas_en_el_predio", "energia_en_el_predio", "telefono_en_el_predio", "rph", "porteria",
                        "citofono", "piscina", "tanque_de_agua", "club_house", "sauna", "vigilancia_privada", "administracion", "club_house"]

# Crea instancias de `LabelEncoder`
encoder = LabelEncoder()

# Aplica la codificación binaria
for columna in columnas_categoricas:
    train_precios['barrio_legal'] = encoder.fit_transform(train_precios['barrio_legal'])
    train_precios['paradero'] = encoder.fit_transform(train_precios['paradero'])
    train_precios['alumbrado'] = encoder.fit_transform(train_precios['paradero'])
    train_precios['arborizacion'] = encoder.fit_transform(train_precios['arborizacion'])
    train_precios['ciclo_rutas'] = encoder.fit_transform(train_precios['ciclo_rutas'])
    train_precios['alcantarillado_en_el_predio'] = encoder.fit_transform(train_precios['alcantarillado_en_el_predio'])
    train_precios['acueducto_en_el_predio'] = encoder.fit_transform(train_precios['acueducto_en_el_predio'])
    train_precios['gas_en_el_predio'] = encoder.fit_transform(train_precios['gas_en_el_predio'])
    train_precios['energia_en_el_predio'] = encoder.fit_transform(train_precios['energia_en_el_predio'])
    train_precios['telefono_en_el_predio'] = encoder.fit_transform(train_precios['telefono_en_el_predio'])
    train_precios['rph'] = encoder.fit_transform(train_precios['rph'])
    train_precios['piscina'] = encoder.fit_transform(train_precios['piscina'])
    train_precios['tanque_de_agua'] = encoder.fit_transform(train_precios['tanque_de_agua'])
    train_precios['club_house'] = encoder.fit_transform(train_precios['club_house'])
    train_precios['sauna'] = encoder.fit_transform(train_precios['sauna'])
    train_precios['vigilancia_privada'] = encoder.fit_transform(train_precios['vigilancia_privada'])
    train_precios['administracion'] = encoder.fit_transform(train_precios['administracion'])
    train_precios['club_house'] = encoder.fit_transform(train_precios['club_house'])
    train_precios['porteria'] = encoder.fit_transform(train_precios['porteria'])
    train_precios['sometido_a_propiedad_horizontal'] = encoder.fit_transform(train_precios['sometido_a_propiedad_horizontal'])
    train_precios['citofono'] = encoder.fit_transform(train_precios['citofono'])
    train_precios['bicicletero'] = encoder.fit_transform(train_precios['bicicletero'])
    train_precios['garaje_visitantes'] = encoder.fit_transform(train_precios['garaje_visitantes'])
    train_precios['teatrino'] = encoder.fit_transform(train_precios['teatrino'])


# Verifica la codificación
print(train_precios.barrio_legal)
print(train_precios.alumbrado)
print(train_precios.arborizacion)
print(train_precios.ciclo_rutas)
print(train_precios.alcantarillado_en_el_predio)
print(train_precios.gas_en_el_predio)
print(train_precios.energia_en_el_predio)
print(train_precios.telefono_en_el_predio)
print(train_precios.rph)
print(train_precios.piscina)
print(train_precios.tanque_de_agua)
print(train_precios.club_house)
print(train_precios.sauna)
print(train_precios.vigilancia_privada)
print(train_precios.administracion)
print(train_precios.club_house)

Generacion modelo de train

In [ ]:
import numpy as np  # Numerical operations
import matplotlib.pyplot as plt  # Data visualization
from sklearn.model_selection import train_test_split  # Data splitting
from sklearn.linear_model import LinearRegression  # Linear regression model
from sklearn.metrics import mean_squared_error, r2_score  # Evaluation metrics

In [ ]:
modelo_train = train_precios

In [ ]:
modelo_train.describe()

,llave_prim,id,barrio_legal,paradero,alumbrado,arborizacion,ciclo_rutas,alcantarillado_en_el_predio,acueducto_en_el_predio,gas_en_el_predio,...,numero_total_depositos,numero_deposito_3,matricula_inmobiliaria_deposito_3,numero_deposito_4,matricula_inmobiliaria_deposito_4,numero_deposito_5,matricula_inmobiliaria_deposito_5,area_privada,valor_area_otros,valor_total_avaluo
count,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,...,10380.000000,10380.000000,10378.0,10380.000000,10379.0,10380.0,10380.0,7644.000000,1.028000e+04,186.000000
mean,6507.941511,9296.717625,0.959110,1.761580,1.761580,0.810962,0.233780,1.018300,1.023028,0.958498,...,0.148362,0.010405,0.0,0.007322,0.0,0.0,0.0,89.457241,4.533289e+06,256.043011
std,3683.836440,5250.836536,0.200242,0.427367,0.427367,0.392672,0.424286,0.299324,0.290983,0.384727,...,0.369562,0.804223,0.0,0.745959,0.0,0.0,0.0,1967.708728,4.335262e+07,243.987213
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,12.000000
25%,3340.000000,4800.000000,1.000000,2.000000,2.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,114.750000
50%,6524.000000,9317.000000,1.000000,2.000000,2.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,51.985000,0.000000e+00,175.000000
75%,9696.000000,13843.000000,1.000000,2.000000,2.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,76.842500,0.000000e+00,295.750000
max,12856.000000,18331.000000,2.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,4.000000,75.000000,0.0,76.000000,0.0,0.0,0.0,160998.340000,1.192110e+09,1764.000000

In [ ]:
test_precios.info

<bound method DataFrame.info of         id       fecha_aprobado       objeto                    motivo  \
0     2243  430.144.469.211.111  Originación  Credito Hipotec Vivienda
1      500  429.894.007.425.116  Originación  Credito Hipotec Vivienda
2    12884                  NaN  Originación  Credito Hipotec Vivienda
3     4019  430.486.908.754.861  Originación   Actualización Garantias
4    11584                  NaN  Originación  Credito Hipotec Vivienda
..     ...                  ...          ...                       ...
412  14877                  NaN  Originación  Credito Hipotec Vivienda
413  11319                  NaN  Originación         Compra de cartera
414   8095                  NaN  Originación  Credito Hipotec Vivienda
415   7435              43158.0  Originación  Credito Hipotec Vivienda
416  16318                  NaN  Originación      Colomext Hipotecario

                proposito  tipo_avaluo tipo_credito tipo_subsidio  \
0    Garantía Hipotecaria  Hipotecario     Vivienda           NaN
1    Garantía Hipotecaria  Hipotecario     Vivienda           NaN
2    Garantía Hipotecaria  Hipotecario     Vivienda           NaN
3    Garantía Hipotecaria  Hipotecario     Vivienda           NaN
4    Garantía Hipotecaria  Hipotecario     Vivienda           NaN
..                    ...          ...          ...           ...
412  Garantía Hipotecaria  Hipotecario     Vivienda           NaN
413  Garantía Hipotecaria  Hipotecario     Vivienda           NaN
414  Garantía Hipotecaria  Hipotecario     Vivienda           VIS
415  Garantía Hipotecaria  Hipotecario     Vivienda      Gratuita
416  Garantía Hipotecaria  Hipotecario     Vivienda           NaN

    departamento_inmueble municipio_inmueble  ... valor_area_terreno  \
0               MAGDALENA        SANTA MARTA  ...                  0
1               MAGDALENA            CIENAGA  ...           27200000
2                  TOLIMA             MELGAR  ...                  0
3                   CESAR         VALLEDUPAR  ...                  0
4                   HUILA           PITALITO  ...                  0
..                    ...                ...  ...                ...
412               BOLIVAR          CARTAGENA  ...           33600000
413          CUNDINAMARCA             CAJICA  ...                  0
414                BOGOTA   BOGOTÃÂ, D. C.  ...           31500000
415             SANTANDER    BARRANCABERMEJA  ...           22000000
416             ANTIOQUIA              BELLO  ...                  0

    area_construccion valor_area_construccion              area_otros  \
0                   0                       0                       0
1                  80                44800000                       0
2                   0                       0                  348.23
3                   0                       0                       0
4                   0                       0  75.239.999.999.999.900
..                ...                     ...                     ...
412                44                39600000                       0
413                 0                       0                       0
414             29.68                23447200                       0
415                56                58240000                       0
416                 0                       0                       0

    valor_area_otros area_libre valor_area_libre      Longitud      Latitud  \
0                  0         No                0           0.0          0.0
1                  0          0                0           0.0          0.0
2           90539800         No                0   -74.643.383    4.203.572
3                  0         Si                0           0.0          0.0
4           41382000         No                0  -760.631.391   18.413.391
..               ...        ...              ...           ...          ...
412                0          0                0    -7.543.036    1.033.191
413                0         Si                0  -740.423.059    4.920.316
414                0          0                0    -7.415.561    4.569.585
415                0          0                0  -746.104.578  104.637.422
416                0         No                0  -755.580.294   63.179.324

    Metro_cuadrado
0              NaN
1              NaN
2     1.711661e+06
3              NaN
4     1.533300e+06
..             ...
412            NaN
413            NaN
414            NaN
415            NaN
416   3.600000e+06

[417 rows x 219 columns]>

In [ ]:
# Crea un  archivo que contenga datos relevante para el mmodelo

train_final_columnas = ['estrato', 'barrio_legal', 'paradero', 'alumbrado', 'arborizacion', 'ciclo_rutas', 'sometido_a_propiedad_horizontal',
                       'porteria', 'citofono', 'bicicletero', 'piscina', 'tanque_de_agua', 'club_house', 'garaje_visitantes',
                       'teatrino', 'sauna', 'vigilancia_privada', 'tipo_vigilancia', 'administracion', 'vetustez', 'habitaciones',
                       'estar_habitacion', 'cuarto_servicio', 'closet', 'sala', 'comedor', 'bano_privado', 'bano_social',
                       'bano_servicio', 'cocina', 'estudio', 'balcon', 'terraza', 'patio_interior', 'jardin', 'zona_de_ropas',
                       'zona_verde_privada', 'local', 'oficina', 'bodega', 'tipo_garaje', 'numero_total_de_garajes', 'area_privada',
                       'valor_area_privada', 'area_garaje', 'valor_area_garaje', 'area_deposito', 'valor_area_deposito', 'area_terreno',
                       'valor_area_terreno', 'area_construccion', 'valor_area_construccion', 'area_otros', 'valor_area_otros',
                       'area_libre', 'valor_area_libre', 'Longitud', 'Latitud', 'valor_total_avaluo']

train_info_modelo = train_precios[train_final_columnas]

train_info_modelo.alumbrado.head()

0    1
1    2
2    2
3    2
4    1
Name: alumbrado, dtype: int64

In [ ]:
Valida_col_train = train_precios['valor_total_avaluo'].value_counts().head(10)
print(Valida_col_train)

valor_total_avaluo
117.0    6
153.0    5
108.0    4
132.0    3
195.0    3
102.0    3
342.0    3
138.0    3
190.0    3
129.0    3
Name: count, dtype: int64

In [ ]:
test_info_modelo.describe()

,barrio_legal,paradero,alumbrado,arborizacion,ciclo_rutas,sometido_a_propiedad_horizontal,porteria,citofono,bicicletero,piscina,...,oficina,bodega,numero_total_de_garajes,area_privada,valor_area_privada,valor_area_garaje,valor_area_deposito,valor_area_construccion,valor_area_otros,valor_area_libre
count,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,417.000000,...,417.000000,417.000000,417.000000,290.000000,4.170000e+02,4.170000e+02,4.170000e+02,4.170000e+02,4.170000e+02,4.170000e+02
mean,0.947242,0.784173,0.784173,0.832134,0.247002,0.071942,0.071942,0.071942,0.071942,1.031175,...,0.002398,0.016787,0.563549,60.945310,1.967126e+08,8.380827e+07,4.037774e+05,2.692603e+07,5.897384e+06,2.924783e+06
std,0.223818,0.411889,0.411889,0.374196,0.431786,0.258703,0.258703,0.258703,0.258703,0.734773,...,0.048970,0.175976,0.617388,121.135175,2.299914e+08,1.566751e+09,1.354450e+06,6.572839e+07,4.439847e+07,2.339788e+07
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,1.000000,52.930000,1.485000e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,...,0.000000,0.000000,1.000000,82.625000,2.661440e+08,1.500000e+07,0.000000e+00,1.890000e+07,0.000000e+00,0.000000e+00
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,...,1.000000,3.000000,3.000000,1869.000000,2.264800e+09,3.200000e+10,1.140000e+07,7.950000e+08,5.901220e+08,3.166856e+08

In [ ]:
train_info_modelo.describe()

,barrio_legal,paradero,alumbrado,arborizacion,ciclo_rutas,sometido_a_propiedad_horizontal,porteria,citofono,bicicletero,piscina,...,jardin,zona_de_ropas,zona_verde_privada,local,oficina,bodega,numero_total_de_garajes,area_privada,valor_area_otros,valor_total_avaluo
count,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,11421.000000,...,10468.000000,10468.000000,10468.000000,10468.000000,10468.000000,10468.000000,10380.000000,7644.000000,1.028000e+04,186.000000
mean,0.959110,1.761580,1.761580,0.810962,0.233780,0.781981,0.673058,0.641450,0.302338,1.131249,...,0.056171,0.971723,0.042893,0.024742,0.009840,0.017864,0.532274,89.457241,4.533289e+06,256.043011
std,0.200242,0.427367,0.427367,0.392672,0.424286,0.527952,0.615275,0.623302,0.607817,0.891007,...,0.238016,0.464630,0.208206,0.207482,0.209634,0.142873,0.650079,1967.708728,4.335262e+07,243.987213
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,12.000000
25%,1.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,114.750000
50%,1.000000,2.000000,2.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,51.985000,0.000000e+00,175.000000
75%,1.000000,2.000000,2.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,2.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,76.842500,0.000000e+00,295.750000
max,2.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,...,4.000000,13.000000,2.000000,10.000000,9.000000,2.000000,5.000000,160998.340000,1.192110e+09,1764.000000

In [ ]:
import os

columnas_comunes =[ 'estrato', 'barrio_legal', 'paradero', 'alumbrado', 'arborizacion', 'ciclo_rutas', 'sometido_a_propiedad_horizontal',
                       'porteria', 'citofono', 'bicicletero', 'piscina', 'tanque_de_agua', 'club_house', 'garaje_visitantes',
                       'teatrino', 'sauna', 'vigilancia_privada', 'tipo_vigilancia', 'administracion', 'vetustez', 'habitaciones',
                       'estar_habitacion', 'cuarto_servicio', 'closet', 'sala', 'comedor', 'bano_privado', 'bano_social',
                       'bano_servicio', 'cocina', 'estudio', 'balcon', 'terraza', 'patio_interior', 'jardin', 'zona_de_ropas',
                       'zona_verde_privada', 'local', 'oficina', 'bodega', 'tipo_garaje', 'numero_total_de_garajes', 'area_privada',
                       'valor_area_privada', 'area_garaje', 'valor_area_garaje', 'area_deposito', 'valor_area_deposito', 'area_terreno',
                       'valor_area_terreno', 'area_construccion', 'valor_area_construccion', 'area_otros', 'valor_area_otros',
                       'area_libre', 'valor_area_libre', 'Longitud', 'Latitud', 'valor_total_avaluo']

valor_total_avaluo_predict = 'columna_precio'

In [ ]:
# 1. Preparar el entorno
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder


# 2. Cargar y preprocesar los datos
# Asume que los archivos subidos son 'datos_con_valores.csv' y 'datos_sin_valores.csv'
datos_sin_valores = test_info_modelo
datos_con_valores = train_info_modelo

# Verificar los datos
print(datos_sin_valores.head(42))
print(datos_con_valores.head(42))

print(datos_con_valores.valor_total_avaluo.head())

# Dividir los datos en características (X) y el objetivo (y)
X = datos_con_valores.drop(columns=['valor_total_avaluo'])
Y = datos_con_valores['valor_total_avaluo']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Entrenar un modelo
modelo = LinearRegression()
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)
error_cuadratico_medio = mean_squared_error(y_test, y_pred)
print(f'Error cuadrático medio: {error_cuadratico_medio}')


# 4. Predecir los valores del otro archivo
X_nuevo = datos_sin_valores
predicciones = modelo.predict(X_nuevo)

# Agregar las predicciones al DataFrame
datos_sin_valores['valor_predio'] = predicciones


# Guardar las predicciones en un nuevo archivo
datos_sin_valores.to_csv('predicciones_valores_predios.csv', index=False)

# Descargar el archivo
files.download('predicciones_valores_predios.csv')

##opcion 2

##columnas_categoricas = ['estrato', 'barrio_legal', 'tipo_vigilancia', 'tipo_garaje', 'area_libre']

##encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
##X_encoded = pd.datos_con_valores(encoder.fit_transform(X[columnas_categoricas]))
##X_encoded.columns = encoder.get_feature_names_out(columnas_categoricas)  # Set column names

##X = X.drop(columnas_categoricas, axis=1)
##X = pd.concat([X, X_encoded], axis=1)

##X_train, X_test

##print(X_train, X_test)



##datos_sin_valores.to_csv('predicciones_valores_predios.csv', index=False)

##files.download('predicciones_valores_predios.csv')

   estrato  barrio_legal  paradero  alumbrado  arborizacion  ciclo_rutas  \
0        5             1         1          1             1            0
1        2             0         1          1             1            0
2        5             1         1          1             1            0
3        4             1         0          0             1            0
4        3             1         0          0             0            0
5        3             1         1          1             1            0
6        2             1         0          0             1            0
7        5             1         1          1             1            1
8        6             1         1          1             1            0
9        3             1         1          1             1            0
10       4             1         1          1             1            0
11       5             1         1          1             1            0
12       3             1         1          1             1            1
13       2             1         1          1             1            1
14       4             1         1          1             1            0
15       2             1         0          0             1            0
16       2             1         1          1             1            0
17       6             1         1          1             1            0
18       3             0         1          1             1            0
19       4             1         1          1             0            0
20       5             1         1          1             1            0
21       2             1         1          1             1            0
22       6             1         0          0             1            0
23       4             1         1          1             1            0
24       3             1         1          1             1            0
25       2             1         1          1             1            1
26       3             1         1          1             0            0
27       4             1         1          1             1            0
28       2             1         0          0             1            0
29       3             1         0          0             1            0
30       4             1         1          1             1            1
31       3             1         1          1             1            0
32       3             1         1          1             1            0
33       5             1         1          1             1            0
34       4             1         0          0             1            0
35       3             1         1          1             0            0
36       1             0         1          1             1            0
37       3             1         1          1             1            1
38       4             1         1          1             1            0
39       4             1         1          1             0            1
40       3             0         1          1             1            0
41       6             1         0          0             1            0

    sometido_a_propiedad_horizontal  porteria  citofono  bicicletero  ...  \
0                                 1         1         1            1  ...
1                                 0         0         0            0  ...
2                                 0         0         0            0  ...
3                                 0         0         0            0  ...
4                                 0         0         0            0  ...
5                                 0         0         0            0  ...
6                                 0         0         0            0  ...
7                                 0         0         0            0  ...
8                                 0         0         0            0  ...
9                                 0         0         0            0  ...
10                                0         0         0            0  ...
11                                0         0         0            0  ...
12                                0         0         0            0  ...
13                                0         0         0            0  ...
14                                0         0         0            0  ...
15                                0         0         0            0  ...
16                                0         0         0            0  ...
17                                0         0         0            0  ...
18                                0         0         0            0  ...
19                                1         1         1            1  ...
20                                0         0         0            0  ...
21                                0         0         0            0  ...
22                                0         0         0            0  ...
23                                0         0         0            0  ...
24                                0         0         0            0  ...
25                                0         0         0            0  ...
26                                0         0         0            0  ...
27                                0         0         0            0  ...
28                                0         0         0            0  ...
29                                1         1         1            1  ...
30                                0         0         0            0  ...
31                                0         0         0            0  ...
32                                0         0         0            0  ...
33                                1         1         1            1  ...
34                                1         1         1            1  ...
35                                0         0         0            0  ...
36                                0         0         0            0  ...
37                                0         0         0            0  ...
38                                0         0         0            0  ...
39                                0         0         0            0  ...
40                                0         0         0            0  ...
41                                1         1         1            1  ...

    area_terreno  valor_area_terreno       area_construccion  \
0              0                   0                       0
1            136            27200000                      80
2              0                   0                       0
3              0                   0                       0
4              0                   0                       0
5            550           232373900                     300
6         104,96            30438400                   80,78
7              0                   0                       0
8              0                   0                       0
9              0                   0                       0
10             0                   0                       0
11           350           327250000                     250
12             0                   0                       0
13             0                   0                       0
14             0                   0                       0
15             0                   0                       0
16            36            76500000                   63.48
17             0                   0                       0
18             0                   0                       0
19             0                   0                       0
20           235           122200000                     214
21            96            22560000                     155
22             0                   0                       0
23             0                   0                       0
24         40,15            20075000                   76,85
25             0                   0                       0
26             0                   0                       0
27           120           174000000  13.480.000.000.000.000
28         110.5            36465000                  135.85
29             0                   0                       0
30             0                   0                       0
31             0                   0                       0
32             0                   0                       0
33             0                   0                       0
34             0                   0                       0
35             0                   0                       0
36           190            47500000                     190
37             0                   0                       0
38             0                   0                       0
39             0                   0                       0
40           115            34500000                     132
41             0                   0                       0

    valor_area_construccion              area_otros  valor_area_otros  \
0                         0                       0                 0
1                  44800000                       0                 0
2                         0                  348.23          90539800
3                         0                       0                 0
4                         0  75.239.999.999.999.900          41382000
5                 795000000                       0                 0
6                  56546000                       0                 0
7                         0                       0                 0
8                         0                       0                 0
9                         0                       0                 0
10                        0                       0                 0
11                314000000                       0                 0
12                        0                       0                 0
13                        0                       0                 0
14                        0                       0                 0
15                        0                       0                 0
16                 62058000                       0                 0
17                        0                       0                 0
18                        0                       0                 0
19                        0                   90.75          45375000
20                 85600000                       0                 0
21                 76725000                       0                 0
22                        0                       0                 0
23                        0                       0                 0
24                 50721000                       0                 0
25                        0                       0                 0
26                        0                       0                 0
27                176048800                       0                 0
28                156227500                       0                 0
29                        0                       0                 0
30                        0                       0                 0
31                        0                       0                 0
32                        0                       0                 0
33                        0                       0                 0
34                        0                       0                 0
35                        0                       0                 0
36                167580000                       0                 0
37                        0                       0                 0
38                        0                       0                 0
39                        0                       0                 0
40                102960000                       8           5200000
41                        0                       0                 0

    area_libre valor_area_libre      Longitud      Latitud
0           No                0           0.0          0.0
1            0                0           0.0          0.0
2           No                0   -74.643.383    4.203.572
3           Si                0           0.0          0.0
4           No                0  -760.631.391   18.413.391
5            0                0           0.0          0.0
6            0                0           0.0          0.0
7           No                0  -740.473.177   47.133.504
8           No                0           0.0          0.0
9           No                0  -764.950.984   34.848.396
10          No                0  -736.470.505   41.391.234
11           0                0   -74.828.406  109.997.219
12          No                0  -755.392.666   63.476.424
13          Si          1010892   -76.616.983    7.882.405
14          No                0  -740.559.106   46.497.259
15          No                0           0.0          0.0
16           0                0  -741.716.923   45.946.587
17          No                0    -7.556.766       61.782
18          No                0           0.0          0.0
19          No                0  -754.491.382  104.181.999
20           0                0           0.0          0.0
21          No                0    -7.480.821    1.091.252
22          No                0           0.0          0.0
23          No                0   -75.588.309   61.644.341
24           0                0           0.0          0.0
25          No                0      -740.449    4.878.105
26          No                0  -754.142.509   69.591.626
27           0                0  -772.900.318   12.170.648
28           0                0  -737.650.334   52.516.757
29          Si                0           0.0          0.0
30          No                0    -7.559.028    6.269.847
31          No                0           0.0          0.0
32          No                0           0.0          0.0
33          No                0           0.0          0.0
34          No                0  -756.225.851   61.448.803
35          No                0           0.0          0.0
36           0                0    -7.661.166    1.021.902
37          Si                0           0.0          0.0
38          No                0  -740.369.515   47.259.732
39          No                0  -740.840.617   46.814.685
40           0                0  -764.911.657    0.4988223
41          Si         31000000           0.0          0.0

[42 rows x 58 columns]
   estrato  barrio_legal  paradero  alumbrado  arborizacion  ciclo_rutas  \
0        1             0         1          1             1            0
1        3             1         2          2             1            0
2        1             1         2          2             1            0
3        2             0         2          2             1            0
4        1             1         1          1             1            0
5        6             1         2          2             1            0
6        3             1         1          1             0            0
7        1             1         2          2             0            0
8        1             1         1          1             1            0
9        1             0         1          1             0            0
10       2             1         1          1             0            0
11       2             1         1          1             1            0
12       1             1         2          2             0            0
13       1             1         2          2             0            0
14       1             1         2          2             1            0
15       1             1         2          2             0            0
16       1             1         1          1             1            0
17       2             0         1          1             1            0
18       1             1         2          2             1            0
19       2             1         2          2             1            0
20       1             0         1          1             1            0
21       1             1         1          1             1            0
22       2             1         1          1             0            0
23       2             1         2          2             0            0
24       1             1         2          2             1            0
25       1             1         2          2             1            0
26       1             1         2          2             1            0
27       2             1         1          1             0            0
28       1             1         2          2             0            0
29       1             1         1          1             1            0
30       2             1         2          2             1            0
31       1             1         1          1             1            0
32       1             1         1          1             0            0
33       4             1         2          2             1            0
34       2             1         2          2             1            0
35       1             1         2          2             1            0
36       2             1         2          2             1            0
37       1             1         2          2             0            0
38       1             1         2          2             1            0
39       1             1         2          2             1            0
40       2             1         1          1             1            0
41       3             1         2          2             1            0

    sometido_a_propiedad_horizontal  porteria  citofono  bicicletero  ...  \
0                                 0         0         0            0  ...
1                                 1         0         0            0  ...
2                                 0         0         0            0  ...
3                                 0         0         0            0  ...
4                                 0         0         0            0  ...
5                                 1         0         1            0  ...
6                                 0         0         0            0  ...
7                                 0         0         0            0  ...
8                                 0         0         0            0  ...
9                                 0         0         0            0  ...
10                                0         0         0            0  ...
11                                0         0         0            0  ...
12                                0         0         0            0  ...
13                                0         0         0            0  ...
14                                0         0         0            0  ...
15                                0         0         0            0  ...
16                                0         0         0            0  ...
17                                1         0         0            0  ...
18                                0         0         0            0  ...
19                                0         0         0            0  ...
20                                0         0         0            0  ...
21                                0         0         0            0  ...
22                                0         0         0            0  ...
23                                0         0         0            0  ...
24                                0         0         0            0  ...
25                                0         0         0            0  ...
26                                0         0         0            0  ...
27                                0         0         0            0  ...
28                                0         0         0            0  ...
29                                0         0         0            0  ...

ValueError: could not convert string to float: 'Comercial'

### **HACER REGRESION LINEAL**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

# ARCHIVOS'
datos_con_valores = train_info_modelo
datos_sin_valores = test_info_modelo

# Verificar los datos
print(datos_con_valores.head())
print(datos_sin_valores.head())

# Dividir los datos en características (X) y el objetivo (y)
X = datos_con_valores.drop(columns=['valor_total_avaluo'])
y = datos_con_valores['valor_total_avaluo']

# Dividir los datos para entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Entrenar un modelo
modelo = LinearRegression()
modelo.fit(X_train, y_train)

# Evaluar el modelo
y_pred = modelo.predict(X_test)
error_cuadratico_medio = mean_squared_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
print(f'Error cuadrático medio: {error_cuadratico_medio}')
print(f'MAPE: {mape}')

# 4. Predecir los valores del otro archivo
X_nuevo = datos_sin_valores
predicciones = modelo.predict(X_nuevo)

# Agregar las predicciones al DataFrame
datos_sin_valores['valor_predio'] = predicciones

# Guardar las predicciones en un nuevo archivo
datos_sin_valores.to_csv('predicciones_valores_predios.csv', index=False)

# Descargar el archivo
files.download('predicciones_valores_predios.csv')

  estrato  barrio_legal  paradero  alumbrado  arborizacion  ciclo_rutas  \
0       1             0         1          1             1            0
1       3             1         2          2             1            0
2       1             1         2          2             1            0
3       2             0         2          2             1            0
4       1             1         1          1             1            0

   sometido_a_propiedad_horizontal  porteria  citofono  bicicletero  ...  \
0                                0         0         0            0  ...
1                                1         0         0            0  ...
2                                0         0         0            0  ...
3                                0         0         0            0  ...
4                                0         0         0            0  ...

   valor_area_terreno  area_construccion  valor_area_construccion  area_otros  \
0            12000000                  0                        0           0
1                   0                  0                        0           0
2            15750000                  0                        0           0
3            16500000                127                      127           0
4            12100000              20,03                  7811700           0

   valor_area_otros  area_libre  valor_area_libre      Longitud     Latitud  \
0               0.0           0                 0           0.0         0.0
1               0.0          No                 0  -755.982.993  62.251.357
2               0.0           0                 0           0.0         0.0
3               0.0           0                 0   -77.280.189   1.194.269
4               0.0           0                 0           0.0         0.0

   valor_total_avaluo
0                12.0
1                 NaN
2                 NaN
3                 NaN
4                 NaN

[5 rows x 59 columns]
  estrato  barrio_legal  paradero  alumbrado  arborizacion  ciclo_rutas  \
0       5             1         1          1             1            0
1       2             0         1          1             1            0
2       5             1         1          1             1            0
3       4             1         0          0             1            0
4       3             1         0          0             0            0

   sometido_a_propiedad_horizontal  porteria  citofono  bicicletero  ...  \
0                                1         1         1            1  ...
1                                0         0         0            0  ...
2                                0         0         0            0  ...
3                                0         0         0            0  ...
4                                0         0         0            0  ...

   area_terreno  valor_area_terreno  area_construccion  \
0             0                   0                  0
1           136            27200000                 80
2             0                   0                  0
3             0                   0                  0
4             0                   0                  0

   valor_area_construccion              area_otros  valor_area_otros  \
0                        0                       0                 0
1                 44800000                       0                 0
2                        0                  348.23          90539800
3                        0                       0                 0
4                        0  75.239.999.999.999.900          41382000

   area_libre valor_area_libre      Longitud     Latitud
0          No                0           0.0         0.0
1           0                0           0.0         0.0
2          No                0   -74.643.383   4.203.572
3          Si                0           0.0         0.0
4          No                0  -760.631.391  18.413.391

[5 rows x 58 columns]

ValueError: could not convert string to float: 'Comercial'

In [ ]:
print(datos_con_valores.describe())
# Guardar las predicciones en un nuevo archivo
datos_con_valores.to_csv('datos_con_valores.csv', index=False)

# Descargar el archivo
files.download('datos_con_valores.csv')

       barrio_legal      paradero     alumbrado  arborizacion   ciclo_rutas  \
count  11421.000000  11421.000000  11421.000000  11421.000000  11421.000000
mean       0.959110      1.761580      1.761580      0.810962      0.233780
std        0.200242      0.427367      0.427367      0.392672      0.424286
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        1.000000      2.000000      2.000000      1.000000      0.000000
50%        1.000000      2.000000      2.000000      1.000000      0.000000
75%        1.000000      2.000000      2.000000      1.000000      0.000000
max        2.000000      3.000000      3.000000      2.000000      2.000000

       sometido_a_propiedad_horizontal      porteria      citofono  \
count                     11421.000000  11421.000000  11421.000000
mean                          0.781981      0.673058      0.641450
std                           0.527952      0.615275      0.623302
min                           0.000000      0.000000      0.000000
25%                           0.000000      0.000000      0.000000
50%                           1.000000      1.000000      1.000000
75%                           1.000000      1.000000      1.000000
max                           2.000000      2.000000      2.000000

        bicicletero       piscina  ...        jardin  zona_de_ropas  \
count  11421.000000  11421.000000  ...  10468.000000   10468.000000
mean       0.302338      1.131249  ...      0.056171       0.971723
std        0.607817      0.891007  ...      0.238016       0.464630
min        0.000000      0.000000  ...      0.000000       0.000000
25%        0.000000      0.000000  ...      0.000000       1.000000
50%        0.000000      1.000000  ...      0.000000       1.000000
75%        0.000000      2.000000  ...      0.000000       1.000000
max        2.000000      3.000000  ...      4.000000      13.000000

       zona_verde_privada         local       oficina        bodega  \
count        10468.000000  10468.000000  10468.000000  10468.000000
mean             0.042893      0.024742      0.009840      0.017864
std              0.208206      0.207482      0.209634      0.142873
min              0.000000      0.000000      0.000000      0.000000
25%              0.000000      0.000000      0.000000      0.000000
50%              0.000000      0.000000      0.000000      0.000000
75%              0.000000      0.000000      0.000000      0.000000
max              2.000000     10.000000      9.000000      2.000000

       numero_total_de_garajes   area_privada  valor_area_otros  \
count             10380.000000    7644.000000      1.028000e+04
mean                  0.532274      89.457241      4.533289e+06
std                   0.650079    1967.708728      4.335262e+07
min                   0.000000       0.000000      0.000000e+00
25%                   0.000000       0.000000      0.000000e+00
50%                   0.000000      51.985000      0.000000e+00
75%                   1.000000      76.842500      0.000000e+00
max                   5.000000  160998.340000      1.192110e+09

       valor_total_avaluo
count          186.000000
mean           256.043011
std            243.987213
min             12.000000
25%            114.750000
50%            175.000000
75%            295.750000
max           1764.000000

[8 rows x 42 columns]

In [ ]:
print(datos_sin_valores.describe())
# Guardar las predicciones en un nuevo archivo
datos_sin_valores.to_csv('datos_sin_valores.csv', index=False)

# Descargar el archivo
files.download('datos_sin_valores.csv')

       barrio_legal    paradero   alumbrado  arborizacion  ciclo_rutas  \
count    417.000000  417.000000  417.000000    417.000000   417.000000
mean       0.947242    0.784173    0.784173      0.832134     0.247002
std        0.223818    0.411889    0.411889      0.374196     0.431786
min        0.000000    0.000000    0.000000      0.000000     0.000000
25%        1.000000    1.000000    1.000000      1.000000     0.000000
50%        1.000000    1.000000    1.000000      1.000000     0.000000
75%        1.000000    1.000000    1.000000      1.000000     0.000000
max        1.000000    1.000000    1.000000      1.000000     1.000000

       sometido_a_propiedad_horizontal    porteria    citofono  bicicletero  \
count                       417.000000  417.000000  417.000000   417.000000
mean                          0.071942    0.071942    0.071942     0.071942
std                           0.258703    0.258703    0.258703     0.258703
min                           0.000000    0.000000    0.000000     0.000000
25%                           0.000000    0.000000    0.000000     0.000000
50%                           0.000000    0.000000    0.000000     0.000000
75%                           0.000000    0.000000    0.000000     0.000000
max                           1.000000    1.000000    1.000000     1.000000

          piscina  ...     oficina      bodega  numero_total_de_garajes  \
count  417.000000  ...  417.000000  417.000000               417.000000
mean     1.031175  ...    0.002398    0.016787                 0.563549
std      0.734773  ...    0.048970    0.175976                 0.617388
min      0.000000  ...    0.000000    0.000000                 0.000000
25%      0.000000  ...    0.000000    0.000000                 0.000000
50%      1.000000  ...    0.000000    0.000000                 1.000000
75%      2.000000  ...    0.000000    0.000000                 1.000000
max      2.000000  ...    1.000000    3.000000                 3.000000

       area_privada  valor_area_privada  valor_area_garaje  \
count    290.000000        4.170000e+02       4.170000e+02
mean      60.945310        1.967126e+08       8.380827e+07
std      121.135175        2.299914e+08       1.566751e+09
min        0.000000        0.000000e+00       0.000000e+00
25%        0.000000        0.000000e+00       0.000000e+00
50%       52.930000        1.485000e+08       0.000000e+00
75%       82.625000        2.661440e+08       1.500000e+07
max     1869.000000        2.264800e+09       3.200000e+10

       valor_area_deposito  valor_area_construccion  valor_area_otros  \
count         4.170000e+02             4.170000e+02      4.170000e+02
mean          4.037774e+05             2.692603e+07      5.897384e+06
std           1.354450e+06             6.572839e+07      4.439847e+07
min           0.000000e+00             0.000000e+00      0.000000e+00
25%           0.000000e+00             0.000000e+00      0.000000e+00
50%           0.000000e+00             0.000000e+00      0.000000e+00
75%           0.000000e+00             1.890000e+07      0.000000e+00
max           1.140000e+07             7.950000e+08      5.901220e+08

       valor_area_libre
count      4.170000e+02
mean       2.924783e+06
std        2.339788e+07
min        0.000000e+00
25%        0.000000e+00
50%        0.000000e+00
75%        0.000000e+00
max        3.166856e+08

[8 rows x 46 columns]

In [ ]:
print(test_precios.describe())
# Guardar las predicciones en un nuevo archivo
test_precios.to_csv('test_precios.csv', index=False)

# Descargar el archivo
files.download('test_precios.csv')

                 id  barrio_legal    paradero   alumbrado  arborizacion  \
count    417.000000    417.000000  417.000000  417.000000    417.000000
mean    8787.635492      0.947242    0.784173    0.784173      0.832134
std     5136.304089      0.223818    0.411889    0.411889      0.374196
min       11.000000      0.000000    0.000000    0.000000      0.000000
25%     4338.000000      1.000000    1.000000    1.000000      1.000000
50%     8799.000000      1.000000    1.000000    1.000000      1.000000
75%    13057.000000      1.000000    1.000000    1.000000      1.000000
max    18270.000000      1.000000    1.000000    1.000000      1.000000

       ciclo_rutas  alcantarillado_en_el_predio  acueducto_en_el_predio  \
count   417.000000                   417.000000              417.000000
mean      0.247002                     0.956835                0.968825
std       0.431786                     0.203474                0.173999
min       0.000000                     0.000000                0.000000
25%       0.000000                     1.000000                1.000000
50%       0.000000                     1.000000                1.000000
75%       0.000000                     1.000000                1.000000
max       1.000000                     1.000000                1.000000

       gas_en_el_predio  energia_en_el_predio  ...  metodo_valuacion_4  \
count        417.000000            417.000000  ...               417.0
mean           0.875300              0.964029  ...                 0.0
std            0.330776              0.186442  ...                 0.0
min            0.000000              0.000000  ...                 0.0
25%            1.000000              1.000000  ...                 0.0
50%            1.000000              1.000000  ...                 0.0
75%            1.000000              1.000000  ...                 0.0
max            1.000000              1.000000  ...                 0.0

       concepto_del_metodo_4  area_privada  valor_area_privada  \
count                  417.0    290.000000        4.170000e+02
mean                     0.0     60.945310        1.967126e+08
std                      0.0    121.135175        2.299914e+08
min                      0.0      0.000000        0.000000e+00
25%                      0.0      0.000000        0.000000e+00
50%                      0.0     52.930000        1.485000e+08
75%                      0.0     82.625000        2.661440e+08
max                      0.0   1869.000000        2.264800e+09

       valor_area_garaje  valor_area_deposito  valor_area_construccion  \
count       4.170000e+02         4.170000e+02             4.170000e+02
mean        8.380827e+07         4.037774e+05             2.692603e+07
std         1.566751e+09         1.354450e+06             6.572839e+07
min         0.000000e+00         0.000000e+00             0.000000e+00
25%         0.000000e+00         0.000000e+00             0.000000e+00
50%         0.000000e+00         0.000000e+00             0.000000e+00
75%         1.500000e+07         0.000000e+00             1.890000e+07
max         3.200000e+10         1.140000e+07             7.950000e+08

       valor_area_otros  valor_area_libre  Metro_cuadrado
count      4.170000e+02      4.170000e+02    1.850000e+02
mean       5.897384e+06      2.924783e+06    3.016216e+06
std        4.439847e+07      2.339788e+07    1.345767e+06
min        0.000000e+00      0.000000e+00    3.150000e+05
25%        0.000000e+00      0.000000e+00    2.120000e+06
50%        0.000000e+00      0.000000e+00    2.700000e+06
75%        0.000000e+00      0.000000e+00    3.750000e+06
max        5.901220e+08      3.166856e+08    8.730000e+06

[8 rows x 92 columns]

In [ ]:
print(train_precios.describe())
# Guardar las predicciones en un nuevo archivo
train_precios.to_csv('train_precios.csv ', index=False)

# Descargar el archivo
files.download('train_precios.csv')

         llave_prim            id  barrio_legal      paradero     alumbrado  \
count  11421.000000  11421.000000  11421.000000  11421.000000  11421.000000
mean    6507.941511   9296.717625      0.959110      1.761580      1.761580
std     3683.836440   5250.836536      0.200242      0.427367      0.427367
min        0.000000      1.000000      0.000000      0.000000      0.000000
25%     3340.000000   4800.000000      1.000000      2.000000      2.000000
50%     6524.000000   9317.000000      1.000000      2.000000      2.000000
75%     9696.000000  13843.000000      1.000000      2.000000      2.000000
max    12856.000000  18331.000000      2.000000      3.000000      3.000000

       arborizacion   ciclo_rutas  alcantarillado_en_el_predio  \
count  11421.000000  11421.000000                 11421.000000
mean       0.810962      0.233780                     1.018300
std        0.392672      0.424286                     0.299324
min        0.000000      0.000000                     0.000000
25%        1.000000      0.000000                     1.000000
50%        1.000000      0.000000                     1.000000
75%        1.000000      0.000000                     1.000000
max        2.000000      2.000000                     2.000000

       acueducto_en_el_predio  gas_en_el_predio  ...  numero_total_depositos  \
count            11421.000000      11421.000000  ...            10380.000000
mean                 1.023028          0.958498  ...                0.148362
std                  0.290983          0.384727  ...                0.369562
min                  0.000000          0.000000  ...                0.000000
25%                  1.000000          1.000000  ...                0.000000
50%                  1.000000          1.000000  ...                0.000000
75%                  1.000000          1.000000  ...                0.000000
max                  2.000000          2.000000  ...                4.000000

       numero_deposito_3  matricula_inmobiliaria_deposito_3  \
count       10380.000000                            10378.0
mean            0.010405                                0.0
std             0.804223                                0.0
min             0.000000                                0.0
25%             0.000000                                0.0
50%             0.000000                                0.0
75%             0.000000                                0.0
max            75.000000                                0.0

       numero_deposito_4  matricula_inmobiliaria_deposito_4  \
count       10380.000000                            10379.0
mean            0.007322                                0.0
std             0.745959                                0.0
min             0.000000                                0.0
25%             0.000000                                0.0
50%             0.000000                                0.0
75%             0.000000                                0.0
max            76.000000                                0.0

       numero_deposito_5  matricula_inmobiliaria_deposito_5   area_privada  \
count            10380.0                            10380.0    7644.000000
mean                 0.0                                0.0      89.457241
std                  0.0                                0.0    1967.708728
min                  0.0                                0.0       0.000000
25%                  0.0                                0.0       0.000000
50%                  0.0                                0.0      51.985000
75%                  0.0                                0.0      76.842500
max                  0.0                                0.0  160998.340000

       valor_area_otros  valor_total_avaluo
count      1.028000e+04          186.000000
mean       4.533289e+06          256.043011
std        4.335262e+07          243.987213
min        0.000000e+00           12.000000
25%        0.000000e+00          114.750000
50%        0.000000e+00          175.000000
75%        0.000000e+00          295.750000
max        1.192110e+09         1764.000000

[8 rows x 69 columns]